---
- name: Add PowerDNS APT key
  apt_key:
    url: https://repo.powerdns.com/FD380FBB-pub.asc

- name: Add dnsdist Apt repository
  apt_repository:
    repo: deb http://repo.powerdns.com/{{ ansible_os_family | lower }} {{ ansible_distribution_release }}-dnsdist-{{ dnsdist_repo_ver }} main
    filename: pdns-dnsdist

- name: Pin dnsdist packages
  copy:
    dest: /etc/apt/preferences.d/pdns-dnsdist
    content: >
      Package: dnsdist*
      Pin: origin repo.powerdns.com
      Pin-Priority: 600
    mode: 0644
    owner: root
    group: root

- name: Update repositories cache
  apt:
    update_cache: yes
  changed_when: false

- name: Install dnsdist server
  apt:
    name: dnsdist
