---
- name: Add PowerDNS APT key
  apt_key:
    url: https://repo.powerdns.com/FD380FBB-pub.asc

- name: Add dnsdist Apt repository
  apt_repository:
    repo: deb http://repo.powerdns.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release }}-dnsdist-{{ dnsdist_repo_ver }} main
    filename: pdns-dnsdist

- name: Pin dnsdist packages
  copy:
    dest: /etc/apt/preferences.d/pdns-dnsdist
    content: >
      Package: dnsdist*
      Pin: origin repo.powerdns.com
      Pin-Priority: 600
    mode: 0644
    owner: root
    group: root

- name: Install dnsdist server
  apt:
    name: dnsdist

- name: Create configuration file
  copy:
    dest: /etc/dnsdist/dnsdist.conf
    content: "{{ dnsdist_config }}"
    mode: 0640
    owner: _dnsdist
    group: _dnsdist
  notify: Restart dnsdist

- name: Create override directory
  file:
    path: /etc/systemd/system/dnsdist.service.d
    state: directory
    owner: root
    group: root
    mode: 0755
  when: dnsdist_limit_nofile is defined

- name: Create override configuration
  template:
    src: nofile.conf.j2
    dest: /etc/systemd/system/dnsdist.service.d/nofile.conf
    owner: root
    group: root
    mode: 0644
  when: dnsdist_limit_nofile is defined
  register: create_override
  notify: Restart dnsdist

- name: Delete override configuration
  file:
    path: /etc/systemd/system/dnsdist.service.d/nofile.conf
    state: absent
  when: dnsdist_limit_nofile is not defined
  register: delete_override
  notify: Restart dnsdist

- name: Reload systemd
  systemd:
    daemon_reload: true
  when: create_override.changed or delete_override.changed

- name: Enable dnsdist
  service:
    name: dnsdist.service
    enabled: yes

- name: Start dnsdist
  service:
    name: dnsdist.service
    state: started
  register: dnsdist_start
