---
- include_tasks: install_apt.yml
  when: ansible_pkg_mgr == "apt"

- include_tasks: install_aur.yml
  when: ansible_pkg_mgr == "pacman"

- name: Create configuration file
  copy:
    dest: /etc/dnsdist.conf
    content: "{{ dnsdist_config }}"
    mode: 0640
    owner: root
    group: root
  notify: Restart dnsdist

- name: Enable dnsdist
  service:
    name: dnsdist.service
    enabled: yes

- name: Start dnsdist
  service:
    name: dnsdist.service
    state: started
  register: dnsdist_start
